### ISSUE TITLE
Consider adding nodeRef to Machine.Status

### ISSUE THREAD

**Issue by mhrivnak** [metalkube/cluster-api-provider-baremetal#48]
It may be a good idea to populate a machine's `Status.NodeRef` so that the MachineSet controller can consider each Machine to be ready.

https://github.com/kubernetes-sigs/cluster-api/blob/0.1.0/pkg/controller/machineset/status.go#L49-L64

**Comment by russellb** [comment]
See this, for where noderef shold be getting set: https://github.com/metalkube/cluster-api-provider-baremetal/blob/master/vendor/sigs.k8s.io/cluster-api/pkg/controller/node/node.go#L76

but that depends on the right annotation being set on Nodes.

This isn't working for us in OpenShift right now.  I'm working through related issues in https://github.com/openshift-metalkube/dev-scripts/issues/260

For a standard Kube environment, I think we'd solve this in a different way.  Based on comments, it sounds like it'd be part of the control plane provisioning code.  Other providers have kubeadm based provisioning code.  I was hoping we'd have optional integration with some shared code, but haven't started looking at it yet.

**Comment by russellb** [comment]
I think we can close this, since this should get set automatically by an existing node controller from cluster-api
